#!/bin/sh
#
# Configure USB gadget interfaces
#

# Set the serial number for the USB gadget
SERIAL_NUMBER="0123456"
# Set the manufacturer name for the USB gadget
MANUFACTURER="My Own"
# Set the product name for the USB gadget
PRODUCT="AA Wireless Dongle"

# Define the names for the accessory and default USB gadgets
ACCESSORY_GADGET_NAME="accessory"
DEFAULT_GADGET_NAME="default"

# Define the path for the FunctionFS
FUNCTIONFS_PATH=/dev/ffs-mtp
# Define the daemon name and PID file path
DAEMON=umtprd
PIDFILE="/var/run/$DAEMON.pid"

RETVAL=0

start() {
	# Start the USB gadget setup process
	printf "Setting up usb_gadgets: "
	mountpoint -q /sys/kernel/config || mount -t configfs none /sys/kernel/config

	# Setup accessory config
	cd /sys/kernel/config/usb_gadget
	if [ ! -d "$ACCESSORY_GADGET_NAME" ]; then
		mkdir "$ACCESSORY_GADGET_NAME"
		cd "$ACCESSORY_GADGET_NAME"
		echo "0x18D1" > idVendor
		echo "0x2D00" > idProduct
		mkdir strings/0x409
		echo "$SERIAL_NUMBER" > strings/0x409/serialnumber
		echo "$MANUFACTURER" > strings/0x409/manufacturer
		echo "$PRODUCT" > strings/0x409/product
		mkdir functions/accessory.usb0
		mkdir configs/c.1
		echo 500 > configs/c.1/MaxPower
		ln -s functions/accessory.usb0 configs/c.1
	fi

	# Setup default config
	cd /sys/kernel/config/usb_gadget
	if [ ! -d "$DEFAULT_GADGET_NAME" ]; then
		mkdir "$DEFAULT_GADGET_NAME"
		cd "$DEFAULT_GADGET_NAME"
		echo "0x18D1" > idVendor
		echo "0x4EE1" > idProduct
		mkdir strings/0x409
		echo "$SERIAL_NUMBER" > strings/0x409/serialnumber
		echo "$MANUFACTURER" > strings/0x409/manufacturer
		echo "$PRODUCT" > strings/0x409/product
		mkdir functions/ffs.mtp
		mkdir configs/c.1
		echo 500 > configs/c.1/MaxPower
		ln -s functions/ffs.mtp configs/c.1
	fi

	# Setting up usb_gadget:
	echo "OK"

	# Start the USB gadget daemon
	printf "Starting $DAEMON: "
	if [ ! -f "$FUNCTIONFS_PATH" ]; then
		mkdir "$FUNCTIONFS_PATH"
	fi
	mount -t functionfs mtp "$FUNCTIONFS_PATH"
	start-stop-daemon -S -b -q -m -p "$PIDFILE" -x "/usr/sbin/$DAEMON"
	RETVAL=$?
	sleep 1
	[ $RETVAL = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	# Stop the USB gadget setup process
	printf "Disabe usb_gadgets: "
	cd /sys/kernel/config/usb_gadget
	echo "" > "$ACCESSORY_GADGET_NAME"/UDC
	echo "" > "$DEFAULT_GADGET_NAME"/UDC

	# Disabe usb_gadget:
	echo "OK"

	# Stop the USB gadget daemon
	printf "Stopping $DAEMON: "
	start-stop-daemon -K -q -s 9 -p "$PIDFILE"
	RETVAL=$?
	umount "$FUNCTIONFS_PATH"
	rm -r "$FUNCTIONFS_PATH"
	[ $RETVAL = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
	# Restart the USB gadget setup process
	stop
	sleep 1
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		;;
esac

exit $RETVAL
